services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    command:
      - go
      - run
      - main.go
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=root
      - DB_PORT=5432
      - GIT_SSL_NO_VERIFY=1  # Ignora verificação SSL no Git
      - GOPROXY=https://goproxy.cn,direct  # Configura proxy para pacotes Go
      - GOINSECURE=github.com
      - GODEBUG=x509ignoreCN=0
      - GIN_GONIC_GIN_IGNORE_CERTS=1
